import { Roboto, Tektur } from 'next/font/google';
import { basePath } from '@/helpers/basePath';
import './globals.css';

const tektur = Tektur({
  variable: '--font-primary',
  subsets: ['cyrillic'],
});

const roboto = Roboto({
  variable: '--font-secondary',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${tektur.variable} ${roboto.variable}`}>
      <body style={{backgroundImage: `url('${basePath}/pattern_dark.png')`}}>
        {children}
      </body>
    </html>
  );
}